#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::home

inscription:
  path: /inscription
  controller: App\Controller\InscriptionController::inscription

product:
    path: /product
    controller: App\Controller\ProductController::product

bag_add:
    path: /bag/{id}
    controller: App\Controller\PaiementController::add

bag:
  path: /bag
  controller: App\Controller\PaiementController::bag

bag_remove:
  path: /bag/remove/{id}
  controller: App\Controller\PaiementController::remove

paiement:
  path: /paiement
  controller: App\Controller\PaiementController::paiement