#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::home

inscription:
  path: /inscription
  controller: App\Controller\InscriptionController::inscription